version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: rsa-php
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    image: rsa-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  backend:
    build:
      context: ./backend-fastapi
      dockerfile: Dockerfile
    image: rsa-backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: rsa-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rsa_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
